services:
    OpcodingAADBundle\Security\AzureAuthenticator:
        class: OpcodingAADBundle\Security\AzureAuthenticator
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            - '@doctrine.orm.entity_manager'

    OpcodingAADBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']